### ISSUE TITLE
no going back

### ISSUE THREAD

**Issue by KevinWMBKit** [KeyboardLogic/KeyboardLogic.SolidEdge.AddIn.ItemCatalog#3]
Hi Ernie, 
After the opening any existing projects in ST9, or creating a new project .asm file in ST9.
 The Library works as it should. However after a save or 2 of the file, the Library looses the ability to go back, and then also looses its ability to select anything again its a total lock up, This is happening on the 3 of 3 of the machines that have gone to the version V.1.0.2

**Comment by eheyder** [comment]
Notes from Kevin:
Seem to have just started with this latest release, but we have all switched to it the latest version now... I must admit we were / are  not all using the Library yet. There are still 2 machines that do not have any version installed yet

**Comment by eheyder** [comment]
Fixed bug in release v1.0.3
